In [1]:
import torch

`cat` does not change the number of dimensions

In [2]:
a = torch.ones(2, 3)
b = torch.zeros(2, 3)

c1 = torch.cat([a, b], dim=0)
c2 = torch.cat([a, b], dim=1)

`stack` changes the number of dimensions

In [3]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

c3 = torch.stack([a, b], dim=0)
c4 = torch.stack([a, b], dim=1)

`view` is a rearrangement of the tensor in-place. `reshape` makes a copy.

x = torch.tensor([1., 2., 3.])
y = torch.tensor([4., 5., 6.])

z1 = torch.dot(x, y)
print(z1)
print(z1.shape)

z2 = torch.outer(x, y)
print(z2)
print(z2.shape)

matmul

In [4]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

z1 = torch.matmul(x, y)
print(z1)
print(z1.shape)

x = x.view(-1, 1)
y = y.view(1, -1)

z2 = torch.matmul(x, y)

tensor(32)
torch.Size([])


matmul only multiplies the final 2 dimensions. Everything else is treated as a batch dimension

e.g. `x = torch.rand(1, 3, 5, 7); y = torch.rand(1, 3, 7, 9)` Then dimensions 5 and 7 in `x` will matmul with 7 and 9 in `y`

In [5]:
x = torch.rand(1, 3, 5, 7)
y = torch.rand(1, 3, 7, 9)

z1 = torch.matmul(x, y)

z2 = torch.matmul(x.view(-1, 5, 7), y.view(-1, 7, 9))

In [6]:
# einsum (Same as above). "Einstein-notation"
z1 = torch.einsum('bijk,bikl->bijl', x, y)

Logsumexp

In [7]:
a = torch.randn(3, 3)
b = torch.logsumexp(a, 1)
print(b)

c = torch.log(torch.sum(torch.exp(a), 1))
print(c)

print(torch.dist(b, c)) # Non-zero due to floating point issues

tensor([1.7235, 0.1871, 0.8988])
tensor([1.7235, 0.1871, 0.8988])
tensor(1.4901e-07)


In [8]:
# Why logsumexp is important
a *= 1000
b = torch.logsumexp(a, 1)
print(b)

c = torch.log(torch.sum(torch.exp(a), 1))

print(torch.dist(b, c))

tensor([1176.7399, -850.8418,    4.2093])
tensor(inf)
